package com.cakeplatform.api.modules.notification;

public enum AdminNotificationType {
    NEW_BAKERY,
    BAKERY_AWAITING_APPROVAL,
    VERIFICATION_SUBMITTED,
    OWNER_FEEDBACK,
    CONTACT_ENQUIRY,
    NEW_ORDER,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,
    BAKERY_SUSPENDED,
    SECURITY_ALERT,
    SYSTEM_ALERT
}
