-- Add new columns to shops table
ALTER TABLE shops ADD COLUMN IF NOT EXISTS business_type VARCHAR(50);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS years_in_business INTEGER;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS fssai_registration VARCHAR(100);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS address_line_1 VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS address_line_2 VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS area VARCHAR(100);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS district VARCHAR(100);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS verification_status VARCHAR(50) DEFAULT 'PROCESSING';

-- Create business_documents table
CREATE TABLE IF NOT EXISTS business_documents (
    id BIGSERIAL PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    document_type VARCHAR(50) NOT NULL,
    file_url VARCHAR(1024) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PROCESSING',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
