import { StorefrontShop, Product } from "@/types/storefront";

export const MOCK_BAKERIES: StorefrontShop[] = [
  {
    id: 1,
    businessName: "Sweet Delight",
    description: "Artisanal boutique bakery specializing in handcrafted floral & custom designer cakes.",
    businessCategory: "Custom Cakes",
    coverImageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    logoUrl: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=200&q=80",
    phone: "+91 98765 43210",
    address: "Shop 4, Akurdi Main Road",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411035",
    rating: 4.8,
    reviewCount: 256,
    deliveryTime: "30-45 mins",
    tags: ["Custom Cakes", "Designer", "Eggless"],
    featuredCategory: "Custom Cakes",
  },
  {
    id: 2,
    businessName: "The Cake Basket",
    description: "Premium Belgian chocolate creations, truffle indulgences and birthday specials.",
    businessCategory: "Chocolate Cakes",
    coverImageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    logoUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=200&q=80",
    phone: "+91 98765 43211",
    address: "Near Elpro Mall, Chinchwad",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411033",
    rating: 4.7,
    reviewCount: 189,
    deliveryTime: "40-60 mins",
    tags: ["Chocolate Cakes", "Truffle", "Cupcakes"],
    featuredCategory: "Chocolate Cakes",
  },
  {
    id: 3,
    businessName: "Bake House",
    description: "Fresh daily bakes, whipped cream photo cakes, and celebration tiered cakes.",
    businessCategory: "Photo Cakes",
    coverImageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
    logoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80",
    phone: "+91 98765 43212",
    address: "Finolex Chowk, Pimpri",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411018",
    rating: 4.6,
    reviewCount: 142,
    deliveryTime: "30-50 mins",
    tags: ["Photo Cakes", "Pastries", "Fresh Fruit"],
    featuredCategory: "Photo Cakes",
  },
  {
    id: 4,
    businessName: "Cake Yard",
    description: "Pure vegetarian & eggless specialty bakery crafting gourmet occasion cakes.",
    businessCategory: "Eggless Cakes",
    coverImageUrl: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80",
    logoUrl: "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=200&q=80",
    phone: "+91 98765 43213",
    address: "Sector 29, Ravet",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "412101",
    rating: 4.9,
    reviewCount: 312,
    deliveryTime: "40-60 mins",
    tags: ["Eggless Cakes", "Pure Veg", "Gourmet"],
    featuredCategory: "Eggless Cakes",
  },
  {
    id: 5,
    businessName: "Warm Whisk",
    description: "Luxury wedding cakes, artisanal cheesecakes, and customized party platters.",
    businessCategory: "Wedding Cakes",
    coverImageUrl: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80",
    logoUrl: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=200&q=80",
    phone: "+91 98765 43214",
    address: "Datta Mandir Road, Wakad",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411057",
    rating: 4.7,
    reviewCount: 176,
    deliveryTime: "30-45 mins",
    tags: ["Wedding Cakes", "Cheesecakes", "French Pastry"],
    featuredCategory: "Wedding Cakes",
  },
  {
    id: 6,
    businessName: "Dessert Studio",
    description: "Trending bento cakes, themed birthday cakes, and freshly whipped treats.",
    businessCategory: "Birthday Cakes",
    coverImageUrl: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80",
    logoUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=200&q=80",
    phone: "+91 98765 43215",
    address: "Phase 1, Hinjawadi",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411057",
    rating: 4.6,
    reviewCount: 195,
    deliveryTime: "40-60 mins",
    tags: ["Birthday Cakes", "Bento Cakes", "Cupcakes"],
    featuredCategory: "Birthday Cakes",
  },
];

export const MOCK_FEATURED_CAKES: Product[] = [
  {
    id: 101,
    name: "Belgian Chocolate Truffle",
    description: "Rich dark chocolate sponge layered with silky Belgian ganache and chocolate curls.",
    price: 650,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    availability: true,
    status: "ACTIVE",
    shopId: 2,
    shopName: "The Cake Basket",
    category: "Chocolate Cakes",
    rating: 4.9,
    dietary: "EGGLESS",
    variants: [
      { id: 1, name: "0.5 kg", price: 450, isAvailable: true },
      { id: 2, name: "1 kg", price: 650, isAvailable: true },
      { id: 3, name: "2 kg", price: 1250, isAvailable: true },
    ],
    addons: [
      { id: 1, name: "Sparkle Candle", price: 50, isAvailable: true },
      { id: 2, name: "Happy Birthday Topper", price: 80, isAvailable: true },
    ],
  },
  {
    id: 102,
    name: "Pink Floral Dream Cake",
    description: "Delicate vanilla bean sponge filled with strawberry compote and buttercream rosettes.",
    price: 850,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    availability: true,
    status: "ACTIVE",
    shopId: 1,
    shopName: "Sweet Delight",
    category: "Custom Cakes",
    rating: 4.8,
    dietary: "REGULAR",
    variants: [
      { id: 4, name: "1 kg", price: 850, isAvailable: true },
      { id: 5, name: "2 kg", price: 1600, isAvailable: true },
    ],
  },
  {
    id: 103,
    name: "Fresh Strawberry Gateau",
    description: "Light chiffon sponge loaded with Mahabaleshwar strawberries and Chantilly cream.",
    price: 750,
    imageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
    availability: true,
    status: "ACTIVE",
    shopId: 3,
    shopName: "Bake House",
    category: "Photo Cakes",
    rating: 4.7,
    dietary: "EGGLESS",
  },
  {
    id: 104,
    name: "Royal Hazelnut Berry Drip",
    description: "Decadent roasted hazelnut praline cake topped with fresh raspberries and chocolate shards.",
    price: 950,
    imageUrl: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80",
    availability: true,
    status: "ACTIVE",
    shopId: 4,
    shopName: "Cake Yard",
    category: "Eggless Cakes",
    rating: 4.9,
    dietary: "EGGLESS",
  },
  {
    id: 105,
    name: "Red Velvet Cream Cheese",
    description: "Classic crimson sponge with Madagascar vanilla infused cream cheese frosting.",
    price: 700,
    imageUrl: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80",
    availability: true,
    status: "ACTIVE",
    shopId: 5,
    shopName: "Warm Whisk",
    category: "Birthday Cakes",
    rating: 4.8,
    dietary: "REGULAR",
  },
  {
    id: 106,
    name: "Biscoff Lotus Cheesecake",
    description: "Creamy baked New York style cheesecake crowned with warm spiced Biscoff spread.",
    price: 890,
    imageUrl: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80",
    availability: true,
    status: "ACTIVE",
    shopId: 6,
    shopName: "Dessert Studio",
    category: "Wedding Cakes",
    rating: 4.9,
    dietary: "EGGLESS",
  },
];
