import { Shop } from '@/types/shop';

export interface IndianCity {
  name: string;
  state: string;
  popularAreas: string[];
}

export interface IndianPlaceOption {
  label: string;
  city: string;
  area?: string;
  state: string;
  isNearby?: boolean;
}

export const INDIAN_POPULAR_PLACES: IndianPlaceOption[] = [
  { label: 'Near by Me (Current Location)', city: 'Near by Me', state: '', isNearby: true },
  { label: 'Pune, Maharashtra', city: 'Pune', state: 'Maharashtra' },
  { label: 'Akurdi, Pune', city: 'Pune', area: 'Akurdi', state: 'Maharashtra' },
  { label: 'Chinchwad, Pune', city: 'Pune', area: 'Chinchwad', state: 'Maharashtra' },
  { label: 'Pimpri, Pune', city: 'Pune', area: 'Pimpri', state: 'Maharashtra' },
  { label: 'Wakad, Pune', city: 'Pune', area: 'Wakad', state: 'Maharashtra' },
  { label: 'Koregaon Park, Pune', city: 'Pune', area: 'Koregaon Park', state: 'Maharashtra' },
  { label: 'Baner, Pune', city: 'Pune', area: 'Baner', state: 'Maharashtra' },
  { label: 'Hinjawadi, Pune', city: 'Pune', area: 'Hinjawadi', state: 'Maharashtra' },
  { label: 'Kothrud, Pune', city: 'Pune', area: 'Kothrud', state: 'Maharashtra' },
  { label: 'Mumbai, Maharashtra', city: 'Mumbai', state: 'Maharashtra' },
  { label: 'Bandra West, Mumbai', city: 'Mumbai', area: 'Bandra West', state: 'Maharashtra' },
  { label: 'Juhu, Mumbai', city: 'Mumbai', area: 'Juhu', state: 'Maharashtra' },
  { label: 'Andheri West, Mumbai', city: 'Mumbai', area: 'Andheri West', state: 'Maharashtra' },
  { label: 'Powai, Mumbai', city: 'Mumbai', area: 'Powai', state: 'Maharashtra' },
  { label: 'Bengaluru, Karnataka', city: 'Bengaluru', state: 'Karnataka' },
  { label: 'Indiranagar, Bengaluru', city: 'Bengaluru', area: 'Indiranagar', state: 'Karnataka' },
  { label: 'Koramangala, Bengaluru', city: 'Bengaluru', area: 'Koramangala', state: 'Karnataka' },
  { label: 'Whitefield, Bengaluru', city: 'Bengaluru', area: 'Whitefield', state: 'Karnataka' },
  { label: 'Delhi NCR', city: 'Delhi NCR', state: 'Delhi' },
  { label: 'Connaught Place, Delhi', city: 'Delhi NCR', area: 'Connaught Place', state: 'Delhi' },
  { label: 'Gurugram, Delhi NCR', city: 'Delhi NCR', area: 'Gurugram', state: 'Haryana' },
  { label: 'Noida, Delhi NCR', city: 'Delhi NCR', area: 'Noida', state: 'Uttar Pradesh' },
  { label: 'Hyderabad, Telangana', city: 'Hyderabad', state: 'Telangana' },
  { label: 'Jubilee Hills, Hyderabad', city: 'Hyderabad', area: 'Jubilee Hills', state: 'Telangana' },
  { label: 'Hitec City, Hyderabad', city: 'Hyderabad', area: 'Hitec City', state: 'Telangana' },
  { label: 'Chennai, Tamil Nadu', city: 'Chennai', state: 'Tamil Nadu' },
  { label: 'Kolkata, West Bengal', city: 'Kolkata', state: 'West Bengal' },
  { label: 'Ahmedabad, Gujarat', city: 'Ahmedabad', state: 'Gujarat' },
  { label: 'Jaipur, Rajasthan', city: 'Jaipur', state: 'Rajasthan' },
];

export const INDIAN_POPULAR_CITIES: IndianCity[] = [
  {
    name: 'Mumbai',
    state: 'Maharashtra',
    popularAreas: ['Bandra West', 'Juhu', 'Powai', 'Andheri West', 'Colaba', 'Dadar', 'Lower Parel'],
  },
  {
    name: 'Pune',
    state: 'Maharashtra',
    popularAreas: ['Koregaon Park', 'Kothrud', 'Viman Nagar', 'Baner', 'Wakad', 'Aundh', 'Kalyani Nagar'],
  },
  {
    name: 'Bengaluru',
    state: 'Karnataka',
    popularAreas: ['Indiranagar', 'Koramangala', 'Whitefield', 'HSR Layout', 'JP Nagar', 'Malleshwaram'],
  },
  {
    name: 'Delhi NCR',
    state: 'Delhi',
    popularAreas: ['Connaught Place', 'South Extension', 'Hauz Khas', 'Gurugram DLF Phase 5', 'Noida Sector 18'],
  },
  {
    name: 'Hyderabad',
    state: 'Telangana',
    popularAreas: ['Jubilee Hills', 'Banjara Hills', 'Hitec City', 'Gachibowli', 'Madhapur', 'Kondapur'],
  },
  {
    name: 'Chennai',
    state: 'Tamil Nadu',
    popularAreas: ['T. Nagar', 'Anna Nagar', 'Adyar', 'Nungambakkam', 'Alwarpet', 'Besant Nagar'],
  },
  {
    name: 'Kolkata',
    state: 'West Bengal',
    popularAreas: ['Park Street', 'Salt Lake Sector 1', 'Ballygunge', 'New Town', 'Alipore', 'Southern Avenue'],
  },
  {
    name: 'Ahmedabad',
    state: 'Gujarat',
    popularAreas: ['Bodakdev', 'Satellite', 'Vastrapur', 'Navrangpura', 'SG Highway', 'Prahlad Nagar'],
  },
  {
    name: 'Jaipur',
    state: 'Rajasthan',
    popularAreas: ['C-Scheme', 'Malviya Nagar', 'Vaishali Nagar', 'Raja Park', 'Mansarovar', 'Civil Lines'],
  },
  {
    name: 'Chandigarh',
    state: 'Punjab',
    popularAreas: ['Sector 17', 'Sector 35', 'Sector 22', 'Sector 8', 'Sector 9', 'Mohali Phase 7'],
  },
  {
    name: 'Kochi',
    state: 'Kerala',
    popularAreas: ['Panampilly Nagar', 'Fort Kochi', 'Marine Drive', 'Kakkanad', 'Edappally'],
  },
  {
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    popularAreas: ['Hazratganj', 'Gomti Nagar', 'Aliganj', 'Indira Nagar', 'Mahanagar'],
  },
];

export const INDIAN_STATES: string[] = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi NCR',
  'Chandigarh',
];

export const MOCK_INDIAN_BAKERIES: Shop[] = [
  {
    id: 1,
    businessName: 'Sweet Delight Artisanal Bakery',
    businessDescription: 'Artisanal boutique bakery specializing in handcrafted floral & custom designer celebration cakes, fresh fruit sponges, and chocolate gateaux.',
    businessType: 'CUSTOM_CAKE_STUDIO',
    businessCategory: 'Custom Cakes',
    phone: '+91 98765 43210',
    addressLine1: 'Shop 4, Near Akurdi Railway Station, Akurdi Main Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411035',
    fssaiRegistration: '11523024000981',
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 284,
    deliveryTimeMinutes: 30,
    coverImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Signature Cakes',
    isPureVeg: false,
    createdAt: '2026-07-15T10:30:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 2,
    businessName: 'The Cake Basket Patisserie',
    businessDescription: 'Premium Belgian chocolate creations, dark truffle indulgences, birthday specials, and slow-baked Lotus Biscoff cheesecakes.',
    businessType: 'PASTRY_SHOP',
    businessCategory: 'Chocolate Cakes',
    phone: '+91 98765 43211',
    addressLine1: 'Near Elpro City Square Mall, Chinchwad Link Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411033',
    fssaiRegistration: '11522038000412',
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 312,
    deliveryTimeMinutes: 25,
    coverImageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Custom Cakes',
    isPureVeg: false,
    createdAt: '2026-07-28T14:15:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 3,
    businessName: 'The Royal Whisk Pastry Studio',
    businessDescription: 'Authentic French entremets, rich red velvet cream cheese cakes, and bespoke multi-tier anniversary centerpieces.',
    businessType: 'PASTRY_SHOP',
    businessCategory: 'Boutique Patisserie',
    phone: '+91 98220 11223',
    addressLine1: 'Lane 7, Near South Main Road, Koregaon Park',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411001',
    fssaiRegistration: '11522038000999',
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 189,
    deliveryTimeMinutes: 35,
    coverImageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Custom Cakes',
    isPureVeg: false,
    createdAt: '2026-07-28T14:15:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 4,
    businessName: 'Delight Confectioneries & Patisserie',
    businessDescription: 'Handcrafted floral celebration cakes, Belgian couverture chocolate gateaux, and artisanal macarons crafted in small batches.',
    businessType: 'CUSTOM_CAKE_STUDIO',
    businessCategory: 'Artisanal Studio',
    phone: '+91 98231 44550',
    addressLine1: 'Shop 14, Heritage Arcade, Linking Road, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    fssaiRegistration: '11523024000981',
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 284,
    deliveryTimeMinutes: 45,
    coverImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Signature Cakes',
    isPureVeg: false,
    createdAt: '2026-07-15T10:30:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 5,
    businessName: 'Saffron & Cocoa Artisan Bakes',
    businessDescription: '100% Pure Vegetarian gourmet bakes combining organic Indian spice infusions with European couverture chocolates.',
    businessType: 'HOME_BAKER',
    businessCategory: 'Pure Veg Specialist',
    phone: '+91 98450 67890',
    addressLine1: '12th Main, 100 Feet Road, HAL 2nd Stage, Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    fssaiRegistration: '11221334000889',
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 198,
    deliveryTimeMinutes: 40,
    coverImageUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Eggless Delights',
    isPureVeg: true,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 6,
    businessName: 'Velvet Ribbon Cake Studio',
    businessDescription: 'Luxurious bespoke tier wedding cakes, edible flower cascades, and signature Belgian dark chocolate truffle towers.',
    businessType: 'CUSTOM_CAKE_STUDIO',
    businessCategory: 'Celebration Cakes',
    phone: '+91 98110 55443',
    addressLine1: 'Block M, Greater Kailash 2, M-Block Market',
    city: 'Delhi NCR',
    state: 'Delhi',
    pincode: '110048',
    fssaiRegistration: '13320005001244',
    status: 'ACTIVE',
    rating: 4.7,
    reviewCount: 220,
    deliveryTimeMinutes: 50,
    coverImageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Wedding Cakes',
    isPureVeg: false,
    createdAt: '2026-08-12T11:45:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 7,
    businessName: 'Pearl City Patisserie',
    businessDescription: 'Contemporary layered desserts, mango passion entremets, pistachio rose cheesecakes, and quick-dispatch tea bakes.',
    businessType: 'PASTRY_SHOP',
    businessCategory: 'Boutique Patisserie',
    phone: '+91 98490 33221',
    addressLine1: 'Road No. 36, Near Peddamma Temple, Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500033',
    fssaiRegistration: '13621014000392',
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 165,
    deliveryTimeMinutes: 35,
    coverImageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Signature Cakes',
    isPureVeg: false,
    createdAt: '2026-08-18T16:20:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 8,
    businessName: 'Grand Parisian Patisserie',
    businessDescription: 'Heritage colonial bakery recipes, fluffy Victoria sponge cakes, rum balls, and rich chocolate fudge slabs.',
    businessType: 'PASTRY_SHOP',
    businessCategory: 'Heritage Bakery',
    phone: '+91 98300 77889',
    addressLine1: '18A, Park Street, Next to Allen Park',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700016',
    fssaiRegistration: '12819001000673',
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 410,
    deliveryTimeMinutes: 40,
    coverImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Classic Cakes',
    isPureVeg: false,
    createdAt: '2026-06-20T10:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 9,
    businessName: 'Madras Sweet & Crust Boutique',
    businessDescription: 'Handcrafted eggless celebration cakes, Lotus Biscoff gateaux, and filter coffee infused tiramisu creations.',
    businessType: 'HOME_BAKER',
    businessCategory: 'Eggless Specialist',
    phone: '+91 98400 99881',
    addressLine1: '45, 2nd Main Road, Gandhi Nagar, Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600020',
    fssaiRegistration: '12421008000551',
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 145,
    deliveryTimeMinutes: 45,
    coverImageUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Eggless Delights',
    isPureVeg: true,
    createdAt: '2026-08-25T13:10:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 10,
    businessName: 'Pink City Royal Confections',
    businessDescription: 'Bespoke royal tier wedding cakes, pistachio cardamom infused sponges, and artisanal celebration dessert tables.',
    businessType: 'CUSTOM_CAKE_STUDIO',
    businessCategory: 'Royal Confections',
    phone: '+91 98290 44332',
    addressLine1: 'Subhash Marg, Near Ahinsa Circle, C-Scheme',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302001',
    fssaiRegistration: '12220026000788',
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 178,
    deliveryTimeMinutes: 50,
    coverImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=200&q=80',
    featuredCategory: 'Custom Cakes',
    isPureVeg: true,
    createdAt: '2026-08-30T09:30:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
];
